// Mini-C programs shared by the compiler (06) and story (08) tests.
module.exports = {
  demo: 'int x = 5;\nint y = x + 3;\nreturn y;',
  sum: 'int total = 0;\nfor (int i = 1; i <= 10; i++) {\n  total = total + i;\n}\nprintf("%d\\n", total);\nreturn total;',
  countdown: 'int n = 5;\nwhile (n > 0) {\n  printf("%d ", n);\n  n--;\n}\nprintf("liftoff\\n");\nreturn 0;',
  maxOf: 'int a = 17, b = 42;\nint m = a > b ? a : b;\nif (m == b) printf("b wins: %d\\n", m);\nelse printf("a wins: %d\\n", m);\nreturn m;',
  precedence: 'int a = 2 + 3 * 4 - 10 / 3 % 2;\nint b = (2 + 3) * (4 - 10) / 3;\nint c = -a * -b + ~a;\nprintf("%d %d %d\\n", a, b, c);\nreturn a + b + c;',
  negDivMod: 'printf("%d %d %d %d\\n", -7 / 2, -7 % 2, 7 / -2, 7 % -2);\nint x = -2147483647 - 1;\nprintf("%d %d\\n", x / 2, x % 3);\nreturn 0;',
  shifts: 'int a = 1 << 10, b = -256 >> 3, n = 5;\nint c = 3 << n, d = 1000 >> n;\nprintf("%d %d %d %d\\n", a, b, c, d);\nreturn (a + b + c + d) & 255;',
  bitwise: 'int a = 0xF0F0, b = 0x0FF0;\nprintf("%x %x %x %X\\n", a & b, a | b, a ^ b, ~a);\nreturn (a ^ b) & 127;',
  logical: 'int a = 0, b = 3, c = 0;\nif (a != 0 && b / a > 1) c = 1;\nif (b > 2 || b / a > 1) c = c + 2;\nint d = !a + !b + (a < b) + (b <= 3) + (a >= b) + (a == 0);\nprintf("%d %d\\n", c, d);\nreturn c * 10 + d;',
  nested: 'int count = 0;\nfor (int i = 0; i < 6; i++) {\n  for (int j = 0; j < i; j++) {\n    if ((i + j) % 3 == 0) continue;\n    if (j > 3) break;\n    count += i * j;\n  }\n}\nprintf("%d\\n", count);\nreturn count;',
  compound: 'int x = 7;\nx += 5; x -= 2; x *= 3; x /= 4; x %= 5;\nx <<= 3; x >>= 1; x |= 9; x &= 13; x ^= 6;\n++x; x++; --x;\nreturn x;',
  shadow: 'int x = 1;\n{\n  int x = 2;\n  x = x + 10;\n  printf("inner %d\\n", x);\n}\nprintf("outer %d\\n", x);\nreturn x;',
  formats: 'int v = 42, w = -7;\nprintf("[%5d][%-4d][%03d][%u][%c][%%]\\n", v, v, v, w, \'i\');\nreturn 0;',
  wrap: 'int big = 2147483647;\nint over = big + 1;\nint prod = 65536 * 65537;\nprintf("%d %d\\n", over, prod);\nreturn 1;',
  fib: 'int a = 0, b = 1;\nfor (int i = 0; i < 20; i++) {\n  int t = a + b;\n  a = b;\n  b = t;\n}\nprintf("fib %d\\n", a);\nreturn a % 256;',
  collatz: 'int n = 27, steps = 0;\nwhile (n != 1) {\n  if (n % 2 == 0) n = n / 2;\n  else n = 3 * n + 1;\n  steps++;\n}\nreturn steps;',
  gcd: 'int a = 1071, b = 462;\nwhile (b != 0) {\n  int t = a % b;\n  a = b;\n  b = t;\n}\nprintf("gcd %d\\n", a);\nreturn a;',
  primes: 'int found = 0;\nfor (int n = 2; n < 60; n++) {\n  int p = 1;\n  for (int d = 2; d * d <= n; d++) {\n    if (n % d == 0) { p = 0; break; }\n  }\n  if (p) { printf("%d ", n); found++; }\n}\nprintf("\\n");\nreturn found;',
  mainFn: '#include <stdio.h>\n\nint main(void) {\n  int x = 12;\n  int y = x * 3 - 4;\n  printf("y = %d\\n", y);\n  return y;\n}',
  ternaryChain: 'int s = 0;\nfor (int i = -3; i <= 3; i++) {\n  s += i < 0 ? -1 : i > 0 ? 1 : 0;\n}\nreturn s + 100;',
  charsHex: "int c = 'A' + 2;\nint h = 0x7f + 0X10;\nprintf(\"%c %d\\n\", c, h);\nreturn h;",
  bigImm: 'int a = 100000;\nint b = a + 70000;\nint c = b - 1000000;\nint d = c * 300;\nint e = d & 0x12345;\nreturn (b + c + d + e) & 255;',
  manyArgs: 'int a = 1, b = 2, c = 3, d = 4, e = 5;\nprintf("%d %d %d %d %d\\n", a + b, b * c, c - d, d * e, e);\nreturn 0;',
  longJump: 'int s = 0;\nfor (int i = 0; i < 3; i++) {\n  s = s + i * 1000 + 1; s = s + i * 1000 + 2; s = s + i * 1000 + 3; s = s + i * 1000 + 4;\n  s = s + i * 1000 + 5; s = s + i * 1000 + 6; s = s + i * 1000 + 7; s = s + i * 1000 + 8;\n  s = s + i * 1000 + 9; s = s + i * 1000 + 10; s = s + i * 1000 + 11;\n}\nreturn s & 255;',
};
